### ISSUE TITLE
Syntax Error while trying to execute OCConfingCompare.command

### ISSUE THREAD

**Issue by 1alessandro1** [corpnewt/OCConfigCompare#1]
Hi, can you provide information on how to use this script?

  File "/Users/user/Desktop/test/OCConfigCompare-master/OCConfigCompare.py", line 98
    print("\nPlist failed to load:  {}\n".format(e),timeout=5)
                                                           ^
SyntaxError: invalid syntax
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by 1alessandro1** [comment]
I've even tried to run that script (the .command file) this way:

sh OCConfigCompare.command config.plist

and the result is:

  ###                      ###
 #     Target Not Found     #
###                      ###

Could not locate OCConfigCompare.py!

the output of ls -l in the current directory is:


6 Mar 19:31 LICENSE
-rwxr-xr-x@ 1 user  staff   7649  6 Mar 19:31 OCConfigCompare.bat
-rwxr-xr-x@ 1 user  staff   7777  6 Mar 19:31 OCConfigCompare.command
-rwxr-xr-x@ 1 user  staff   6979  6 Mar 19:31 OCConfigCompare.py
-rwxr-xr-x@ 1 user  staff     87  6 Mar 19:31 README.md
-rwxr-xr-x@ 1 user  staff  21120 11 Mar 16:11 Sample.plist
drwxr-xr-x@ 6 user  staff    192  6 Mar 19:31 Scripts
-rw-r--r--@ 1 user  staff  11333  4 Mar 20:32 config.plist

P.S. As you can see I added executable properties to Both of them - even to those in the Scripts Folder

**Comment by 1alessandro1** [comment]
Hi, I found the issue: the python version I'm currently using is python2.7 but this script requires at least python3.x - is it possible to adapt the same script to previous python versions? 

If it isn't, don't worry I'll solve the problem installing python3 (but other people may be unaware on how to solve this if they run this script on macOS which uses Python 2 by default)

Let me know, thanks

**Comment by corpnewt** [comment]
Should be fixed in [this commit](https://github.com/corpnewt/OCConfigCompare/commit/00e1dd24bed038019b10fea461356982e14eb200).  The issue was on my end, but not something triggered by py3, so I didn't notice it before.  Thanks.

-CorpNewt
