### ISSUE TITLE
OCConfigCompare need to improve.

### ISSUE THREAD

**Issue by OnSale1980** [corpnewt/OCConfigCompare#10]
even though this script work good but there one thing need to be fix which is involved in amd kernel patch (or Kernel patch). if the the current kernel patch have 22 Childs but you if only add 2 childs to kernel patch it will not tell you that u need to fix kernel b/c it's meet the requirement. take example the picture I show below or attachment to this post
![Screen Shot 2023-09-25 at 6 02 32 PM](https://github.com/corpnewt/OCConfigCompare/assets/51124456/98b57171-8982-483e-82d5-d9e0f20653b3)
![Screen Shot 2023-09-25 at 6 02 44 PM](https://github.com/corpnewt/OCConfigCompare/assets/51124456/899294ef-fd0c-47dd-a3c1-3b77185200c2)

**Comment by corpnewt** [comment]
You can enable checking all values, and values within arrays from the menu - but the point of OCConfigCompare is not to interpret a config.plist for one machine or another - but instead to compare keys to tell you if something is missing/erroneous.  The AMD kernel patches would fall under the blanket of "interpreting the config.plist", and are outside the scope of this.  If you want a tool to add/update/etc those, you can look at my [AMDVanillaPatches](https://github.com/corpnewt/AMDVanillaPatches) script instead.

-CorpNewt
