### ISSUE TITLE
About SysReport missing

### ISSUE THREAD

**Issue by rpijoan-nutriconsell** [corpnewt/OCConfigCompare#3]
Hi,

Should SysReport be flagged as missing if is not supported in 0.5.9 release? OpenCore [differences.pdf](https://github.com/acidanthera/OpenCorePkg/blob/0.5.9/Docs/Differences/Differences.pdf) in part 8.4.6 is specified only for Debug build because of security reasons.

**Comment by corpnewt** [comment]
OCConfigCompare doesn't interpret any of the values contained in each plist - it just compares whether or not they exist to assist with what to look at when updating.  It is still the responsibility of the user to know *how* to update their config.

-CorpNewt
