### ISSUE TITLE
Error: name 'long' is not defined

### ISSUE THREAD

**Issue by kirkcharlesniv** [corpnewt/OCConfigCompare#5]
MRE:

1. Select your user config plist
2. Press 5 to compare

![Screen Shot 2020-12-13 at 8 24 01 PM](https://user-images.githubusercontent.com/19856377/102011730-240f7380-3d81-11eb-90c5-e64211f93336.png)

**Comment by qqsir-dev** [comment]
same issue

**Comment by corpnewt** [comment]
Should be fixed in [this commit](https://github.com/corpnewt/OCConfigCompare/commit/41f67a098aac6166ccd009145d427259874e4bff).

-CorpNewt
