### ISSUE TITLE
Space in CLI arguments

### ISSUE THREAD

**Issue by hacker1024** [corpnewt/OCConfigCompare#6]
When using CLI arguments, spaces are not handled correctly.
For example, my EFI partition is unlabelled and mounts as `NO NAME`:

```
$ ./OCConfigCompare.command -u /Volumes/NO\ NAME/EFI/OC/config.plist -s ~/Downloads/OpenCore-0.6.8-RELEASE/Docs/Sample.plist

usage: OCConfigCompare.py [-h] [-u USER_PLIST] [-s SAMPLE_PLIST]
OCConfigCompare.py: error: unrecognized arguments: NAME/EFI/OC/config.plist
```

**Comment by corpnewt** [comment]
I pushed a fix recently that treats args passed to the .command as an array - which preserves escapes and quoted vars.

-CorpNewt

**Comment by hacker1024** [comment]
That's fixed it, thanks!
