### ISSUE TITLE
Missing Keys in config.plist to reflect OC 072 feature-set

### ISSUE THREAD

**Issue by 5T33Z0** [corpnewt/OCConfigCompare#7]
Hi. I just generated a config for Coffeelake and noticed some missing keys. They are:

- Kernel > Scheme > CustomKernel
- UEFI > AppleInput > GraphicsInputMirroring

**Comment by corpnewt** [comment]
Hey there - not sure what this issue implies regarding OCConfigCompare though?  Could you elaborate more on what the problem with the script is?

-CorpNewt

**Comment by 5T33Z0** [comment]
Ups, this was meant for a complety different github project by somebody else (OC Gen X). I guess I had the wrong Tab open. Sorry.

**Comment by corpnewt** [comment]
Not a problem!  Best of luck, and happy hacking 👍 

-CorpNewt
