### ISSUE TITLE
Plist faild to load

### ISSUE THREAD

**Issue by Benecke** [corpnewt/OCConfigCompare#8]
Tool used to work flawlessly until now. Getting `Plist failed to load:  __init__() got an unexpected keyword argument 'use_builtin_types'` after downloading the latest Sample.plist

It also happens when downloading OC (https://github.com/acidanthera/OpenCorePkg/releases) manually and drag-dropping the plist into the terminal.

Using on OSX 11.6 (20G165)
OpenCore version 0.76

```
#######################################################
 #                 OC Config Compare                   #
#######################################################

Gathering latest Sample.plist from:
https://github.com/acidanthera/OpenCorePkg/raw/master/Docs/Sample.plist

Loading... 38.03 KB of 38.03 KB (100.00%)

Plist failed to load:  __init__() got an unexpected keyword argument 'use_builtin_types'

Press [enter] to return...
```

**Comment by corpnewt** [comment]
I bet I know the issue - I believe it's related to the python version.  I'll double check and push a fix if need be 👍 

-CorpNewt

**Comment by corpnewt** [comment]
A fix was already implemented in [this commit](https://github.com/corpnewt/OCConfigCompare/commit/9dafdf254c42fe96ba1a813dcf77225b563f6d3e#diff-030cb7b648f7c9b3d2dadb09cbd9567824fcd6567c226dcb0cd84a042a9b38f1) some time ago (October of 2020):

```py
        try:
            p = P(use_builtin_types=use_builtin_types, dict_type=dict_type)
        except:
            # Python 3.9 removed use_builtin_types
            p = P(dict_type=dict_type)
```

Are you sure you're running the latest copy of OCConfigCompare?

-CorpNewt

**Comment by Benecke** [comment]
Duh! 🤦 You're right, it works just fine with the current version. Sorry for wasting your time but thank you for the quick reply and pointing me to it.

I guess I was looking at the releases block here at github and as you're not using the feature, I somehow came to the conclusion that there are no new releases.
