### ISSUE TITLE
Comparing arrays BUG

### ISSUE THREAD

**Issue by syakiba** [corpnewt/OCConfigCompare#9]
the user ary[0] vs the oc ary[0] = ok
the user ary[1] vs **the oc ary[0]** = no (the correct OC.plist ary index is 1)
the user ary[2] vs **the oc ary[0]** = no (the correct OC.plist ary index is 2)
![image](https://github.com/corpnewt/OCConfigCompare/assets/85938202/0f198c2a-c49c-462b-a2f6-76e70a4130cf)
the test files:
[the OC config](https://github.com/syakiba/plistCompare/blob/master/the%20OC.plist)
[the User config](https://github.com/syakiba/plistCompare/blob/master/the%20User.plist)

**Comment by corpnewt** [comment]
~~It's not a bug - array order is still something to consider, and should be reported.  If you diffed 2 config.plists with different kext load order, you wouldn't want the tool to say they're the same when one works and another doesn't, right?~~

-CorpNewt

***

In looking at the screenshots - I think I see what you mean.  All of the array entries from the user provide plist are being compared against the entry at the 0 index for the sample entry.  Hmm..... I'll have to see what I can do about that.  Thanks for the info.

**Comment by corpnewt** [comment]
Please give the updated commit a try and let me know if that works/doesn't work.

-CorpNewt

**Comment by syakiba** [comment]
wow it is runing correctly now, thank you for your work ^^
